[project]
name = "hpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.0",
    "tyro>=1.0.3",
]

[dependency-groups]
dev = [
    "vulture>=2.14",
]
